### ISSUE TITLE
Use LeapHybridSampler

### ISSUE THREAD

**Issue by hsadeghidw** [dwave-examples/structural-imbalance#23]
Currently, the sampler is hardcoded in the demo.

Either change to use LeapHybridSampler or allow the user to pick the sampler with the set of parameters.

In the demo, the results are plotted and saved. Display them instead.

@arcondello 
@randomir

**Comment by arcondello** [comment]
To clarify, you'd like a new [usage](https://github.com/dwave-examples/structural-imbalance#usage) Option C
```
python demo.py leaphybrid
```
or similar?

Also, the option to display, so maybe something like
```
python demo.py leaphybrid --show-plot
```
or something like that?

**Comment by hsadeghidw** [comment]
That works. Currently, the solver is hardcoded and the plots are saved as file.
