### ISSUE TITLE
CI failing due to "no embedding found"

### ISSUE THREAD

**Issue by mcfarljm** [dwave-examples/structural-imbalance#33]
The unit tests do pass for me locally with DW_2000Q_6 and Advantage.  Is there a different QPU architecture that is being used by Circle CI?  The fix may be to use a `--region` flag to define a smaller problem when running `structural_imablance.py` in the unit test.

**Comment by arcondello** [comment]
I expect it's picking up a 2000Q. We can specify advantage, something like `DWaveSampler(solver=dict(topology__type='pegasus'))`

**Comment by randomir** [comment]
We can also ask for a bigger QPU:
```
DWaveSampler(solver=dict(order_by='-num_qubits'))
```
